version: "3.5"
services:
  web:
    container_name: social-network-study
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mysql-db
    networks:
      - social-network

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    hostname: mysql-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/mysql-db:/var/lib/mysql
      - ./logs/mysql-db:/var/log/mysql
      - ./config/mysql-master/mysql.conf.cnf:/etc/mysql/mysql.conf.d/mysql.conf.cnf
    networks:
      - social-network

#  mysql-db-slave-1:
#    image: mysql:5.7
#    container_name: mysql-db-slave-1
#    hostname: mysql-db-slave-1
#    ports:
#      - 3380:3306
#    environment:
#      - MYSQL_ROOT_HOST=${DB_HOST_SLAVE_1}
#      - MYSQL_USER=${DB_USERNAME}
#      - MYSQL_PASSWORD=${DB_PASSWORD}
#      - MYSQL_DATABASE=${DB_NAME}
#      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#    volumes:
#      - ./data/mysql-slave-1:/var/lib/mysql
#      - ./logs/mysql-slave-1:/var/log/mysql
#      - ./config/mysql-slave-1/mysql.conf.cnf:/etc/mysql/mysql.conf.d/mysql.conf.cnf
#    networks:
#      - social-network
#    depends_on:
#      - mysql-db
#
#  mysql-db-slave-2:
#    image: mysql:5.7
#    container_name: mysql-db-slave-2
#    hostname: mysql-db-slave-2
#    ports:
#      - 3381:3306
#    environment:
#      - MYSQL_ROOT_HOST=${DB_HOST_SLAVE_2}
#      - MYSQL_USER=${DB_USERNAME}
#      - MYSQL_PASSWORD=${DB_PASSWORD}
#      - MYSQL_DATABASE=${DB_NAME}
#      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#    volumes:
#      - ./data/mysql-slave-2:/var/lib/mysql
#      - ./logs/mysql-slave-2:/var/log/mysql
#      - ./config/mysql-slave-2/mysql.conf.cnf:/etc/mysql/mysql.conf.d/mysql.conf.cnf
#    networks:
#      - social-network
#    depends_on:
#      - mysql-db


# Networks to be created to facilitate communication between containers
networks:
  social-network:
    driver: bridge