# Server configurations
server:
  port: 8080

# Database credentials
database:
  user: b650090eef2e23
  pass: 234189f2
  hosts:
#    - mysql-db-slave-2:3306
#    - mysql-db-slave-1:3306
    - us-cdbr-east-04.cleardb.com
  name: heroku_e54883ae12df5b5

